apiVersion: v1
kind: Namespace
metadata:
  name: big-data
  labels:
    name: big-data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-env
  namespace: big-data
data:
  YARN_CONF_yarn_log_server_url: https://historyserver:8188/applicationhistory/logs/
  YARN_CONF_yarn_resourcemanager_hostname: resourcemanager
  YARN_CONF_yarn_resourcemanager_address: resourcemanager:8032
  YARN_CONF_yarn_resourcemanager_scheduler_address: resourcemanager:8030
  YARN_CONF_yarn_resourcemanager_resource__tracker_address: resourcemanager:8031
  YARN_CONF_yarn_timeline___service_hostname: historyserver
  MAPRED_CONF_mapred_child_java_opts: "-Xmx4096m"
  MAPRED_CONF_mapreduce_jobhistory_address: historyserver:10020
  MAPRED_CONF_mapreduce_jobhistory_webapp_address: historyserver:19888
  CORE_CONF_fs_defaultFS: "hdfs://namenode:9000"
  HADOOP_URL: "hdfs://namenode:9000"
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: big-data
spec:
  selector:
    app: namenode
  clusterIP: None
  externalName: namenode
  ports:
    - name: web-ui
      port: 9870
      targetPort: 9870
    - name: namenode-ipc
      port: 9000
      targetPort: 9000  
---
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
  namespace: big-data
spec:
    selector:
      app: resourcemanager
    clusterIP: None
    externalName: resourcemanager
    ports:
      - name: yarn-web-ui
        port: 8088
        targetPort: 8088
      - name: yarn-scheduler
        port: 8030
        targetPort: 8030
      - name: yarn-jobtracker
        port: 8031
        targetPort: 8031
      - name: yarn
        port: 8032
        targetPort: 8032 
---
apiVersion: v1
kind: Service
metadata:
  name: historyserver
  namespace: big-data
spec:
  selector:
    app: historyserver
  clusterIP: None
  externalName: historyserver
  ports:
    - name: web-ui
      port: 19888
      targetPort: 19888
    - name: ipc
      port: 10200
      targetPort: 10200
    - name: other-web-ui
      port: 8188
      targetPort: 8188
---
apiVersion: v1
kind: Service
metadata: 
  name: datanode
  namespace: big-data
spec:
  selector:
    app: datanode
  clusterIP: None
  ports:
    - name: datanode-ipc
      port: 9864
      targetPort: 9864
---
apiVersion: v1
kind: Pod
metadata:
  name: namenode
  namespace: big-data
  labels:
    app: namenode
spec:
  volumes:
    - name: vol
  containers:
  - name: namenode
    image: duynguyenngoc/hadoop-namenode:3.3.2
    imagePullPolicy: Never
    envFrom:
    - configMapRef:
        name: hadoop-env
    ports:
      - containerPort: 9870
      - containerPort: 9000
      - containerPort: 9866
    volumeMounts:
      - name: vol
        mountPath: /hadoop/dfs/name
---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: datanode
  namespace: big-data
  labels:
    app: datanode
spec:
  serviceName: "datanode"
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - image: duynguyenngoc/hadoop-datanode:3.3.2
          name: datanode
          imagePullPolicy: Never
          env:
          - name: SERVICE_PRECONDITION
            value: "namenode:9000 namenode:8080"
          - name: NUM_CORES
            value: "2"
          envFrom:
          - configMapRef:
              name: hadoop-env
          volumeMounts:
            - mountPath: /hadoop/dfs/data
              name: vol 
          ports:
            - containerPort: 8081
            - containerPort: 4040
            - containerPort: 50020
        - image: duynguyenngoc/hadoop-nodemanager:3.3.2
          name: nodemanager
          imagePullPolicy: Never
          ports:
            - containerPort: 45454
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SERVICE_PRECONDITION
            value: "namenode:9000 resourcemanager:8088 $(POD_NAME):50020"
          envFrom:
          - configMapRef:
              name: hadoop-env
      volumes:
        - name: vol
---
apiVersion: v1
kind: Pod
metadata:
  name: resourcemanager
  namespace: big-data
  labels: 
    app: resourcemanager
spec: 
  containers:
    - image: duynguyenngoc/hadoop-resourcemanager:3.3.2
      name: resourcemanager
      imagePullPolicy: Never
      env:
      - name: SERVICE_PRECONDITION
        value: "namenode:9000 datanode:8081"
      envFrom:
      - configMapRef:
          name: hadoop-env
      ports:
        - containerPort: 8088
        - containerPort: 8031
        - containerPort: 8032
        - containerPort: 8030
      readinessProbe:
        exec:
          command:
          - curl 
          - -sI 
          - datanode:8081
        initialDelaySeconds: 2
        periodSeconds: 3
---
apiVersion: v1
kind: Pod
metadata:
  name: historyserver
  namespace: big-data
  labels: 
    app: historyserver
spec:
  containers:
    - image: duynguyenngoc/hadoop-historyserver:3.3.2
      name: historyserver
      imagePullPolicy: Never
      env:
      - name: SERVICE_PRECONDITION
        value: "namenode:9000 datanode:8081"
      envFrom:
      - configMapRef:
          name: hadoop-env
      ports:
        - containerPort: 8188
        - containerPort: 19888
        - containerPort: 10200  
      volumeMounts:
        - name: historyserver
          mountPath: /hadoop/yarn/timeline
  volumes:
    - name: historyserver