######################################################################
# IMAGE for airflow
######################################################################
FROM duynguyenngoc/hadoop-airflow:3.3.2

LABEL maintainer="Duy Nguyen <duyngunyenngoc@hotmail.com>"

WORKDIR /airflow/


# Install Requirement python3 pip
# COPY ./requirements.txt /requirements.txt

RUN pip3 install pyarrow pillow

COPY ./app/ /airflow/

EXPOSE 8080
